# Generated by Django 4.1.1 on 2022-10-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_empmodel_gender_remove_empmodel_occupation_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empmodel',
            table='tbl_emp_data',
        ),
    ]
